runtime: nodejs18 # or another supported version

instance_class: F2

env_variables:
  PORT: "3000"
  MONGODB_URI: "mongodb+srv://Admin:45dylWbu0dDBNCDz@main.39e1u.mongodb.net/Early-Access?retryWrites=true&w=majority"
  OPENAI_API_KEY: "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"

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto