branch-defaults:
  default:
    environment: server
    group_suffix: null
  main:
    environment: server
global:
  application_name: Server
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
